# Travis-CI script to install & test MOOSE with NeuroML

notifications:
    email:
        recipients:
            - dilawar.s.rajput@gmail.com

install:
  - sudo add-apt-repository -y ppa:bhallalab/moose
  - sudo apt-get update
  - sudo apt-get install moose-python 
  - sudo apt-get install python-pip python-networkx
  - pip install pygraphviz --upgrade -y 

script:
  - ( cd ./test && ./test_all.sh )

