
# /home/dilawars/Work/BhallaLab/moose-chemical/reaction_scheme_reader/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '0546E42D1F929ED01BC126CAED9A87FA'
    
_lr_action_items = {'RPAREN':([10,12,17,20,],[-2,16,-8,-3,]),'NAME':([0,5,6,7,14,15,21,],[3,3,9,9,3,9,3,]),'RIGHT_REAC':([10,11,17,20,],[-2,14,-8,-3,]),'DECIMAL':([13,],[17,]),'EQUALS':([9,],[13,]),'PLUS':([2,4,8,16,18,19,22,],[5,-4,-5,-9,21,-6,-7,]),'LPAREN':([3,],[7,]),'LEFT_REAC':([2,4,8,16,],[6,-4,-5,-9,]),'COMMA':([10,11,12,17,20,],[-2,15,15,-8,-3,]),'$end':([1,16,18,19,22,],[0,-9,-1,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'reaction':([0,],[1,]),'reactants':([0,],[2,]),'param':([6,7,15,],[10,10,20,]),'products':([14,],[18,]),'params':([6,7,],[11,12,]),'species':([0,5,14,21,],[4,8,19,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> reaction","S'",1,None,None,None),
  ('reaction -> reactants LEFT_REAC params RIGHT_REAC products','reaction',5,'p_reaction','chem_parser.py',30),
  ('params -> param','params',1,'p_params','chem_parser.py',36),
  ('params -> params COMMA param','params',3,'p_params','chem_parser.py',37),
  ('reactants -> species','reactants',1,'p_reactants','chem_parser.py',42),
  ('reactants -> reactants PLUS species','reactants',3,'p_reactants','chem_parser.py',43),
  ('products -> species','products',1,'p_products','chem_parser.py',49),
  ('products -> products PLUS species','products',3,'p_products','chem_parser.py',50),
  ('param -> NAME EQUALS DECIMAL','param',3,'p_param','chem_parser.py',55),
  ('species -> NAME LPAREN params RPAREN','species',4,'p_species','chem_parser.py',61),
]
